### ISSUE TITLE
Python version requirement too stringent?

### ISSUE THREAD

**Issue by me21** [uktrade/stream-zip#32]
Setup.py states that Python version should be >= 3.7.4. Why exactly does it require specific patch version? Why not Python >= 3.7?

**Comment by michalc** [comment]
I think at the time we couldn't quite figure out (at least in a reasonable amount of time) how to test on a Python version earlier than 3.7.4, so didn't want to put an earlier patch version.

That was on CircleCI, and [we now run tests on GitHub actions](https://github.com/uktrade/stream-zip/commit/9739b6a2d7da607230f827447761101bda7c46f2), so it might be easier to run tests on earlier versions. I'll have a nose around...

Just to check though, is this causing you problems?

**Comment by me21** [comment]
I was evaluating several packages for zip streaming and I couldn't install it on a single board computer running Debian 10 and Python 3.7.3

**Comment by michalc** [comment]
Ah understood. Working on https://github.com/uktrade/stream-zip/pull/33 now that adds support for Python 3.7.1 onwards, and if all goes well, should be released in the next hour or so

**Comment by michalc** [comment]
Done. Released in v0.0.59:

https://pypi.org/project/stream-zip/0.0.59/
https://github.com/uktrade/stream-zip/releases/tag/v0.0.59
