### ISSUE TITLE
Switch from legacy MS-DOS timestamps to extra-timestamp (UNIX time)

### ISSUE THREAD

**Issue by Arcitec** [uktrade/stream-zip#57]
Hi! :)

The legacy MS-DOS way of storing ZIP "modification timestamps" are using basic local time, with 2-second precision, and completely lacks any timezone information. So if I pack a file in Sweden and you unzip it in America, you'll get the wrong timestamps on all extracted files. All ZIP extraction utilities interpret the MS-DOS timestamp as local time, since that's unfortunately the standard (I wish Phil Katz had the foresight to at least store it in GMT/UTC time, but sadly not.)

All ZIP utilities these days (ever since 1997) therefore use the modern way of storing time in ZIP files, via the "extra" field extensions. To be precise, they use this extension:

- `0x5455 extended timestamp`, which is the UNIX timestamp (UTC), for perfect, universal precision. It's a massive upgrade for the timestamp precision of ZIP files.

[Described as follows](https://opensource.apple.com/source/zip/zip-6/unzip/unzip/proginfo/extra.fld):

```
         -Extended Timestamp Extra Field:
          ==============================

          The following is the layout of the extended-timestamp extra block.
          (Last Revision 19970118)

          Local-header version:

          Value         Size        Description
          -----         ----        -----------
  (time)  0x5455        Short       tag for this extra block type ("UT")
          TSize         Short       total data size for this block
          Flags         Byte        info bits
          (ModTime)     Long        time of last modification (UTC/GMT)
          (AcTime)      Long        time of last access (UTC/GMT)
          (CrTime)      Long        time of original creation (UTC/GMT)

          Central-header version:

          Value         Size        Description
          -----         ----        -----------
  (time)  0x5455        Short       tag for this extra block type ("UT")
          TSize         Short       total data size for this block
          Flags         Byte        info bits (refers to local header!)
          (ModTime)     Long        time of last modification (UTC/GMT)

          The central-header extra field contains the modification time only,
          or no timestamp at all.  TSize is used to flag its presence or
          absence.  But note:

              If "Flags" indicates that Modtime is present in the local header
              field, it MUST be present in the central header field, too!
              This correspondence is required because the modification time
              value may be used to support trans-timezone freshening and
              updating operations with zip archives.

          The time values are in standard Unix signed-long format, indicating
          the number of seconds since 1 January 1970 00:00:00.  The times
          are relative to Coordinated Universal Time (UTC), also sometimes
          referred to as Greenwich Mean Time (GMT).  To convert to local time,
          the software must know the local timezone offset from UTC/GMT.

          The lower three bits of Flags in both headers indicate which time-
          stamps are present in the LOCAL extra field:

                bit 0           if set, modification time is present
                bit 1           if set, access time is present
                bit 2           if set, creation time is present
                bits 3-7        reserved for additional timestamps; not set

          Those times that are present will appear in the order indicated, but
          any combination of times may be omitted.  (Creation time may be
          present without access time, for example.)  TSize should equal
          (1 + 4*(number of set bits in Flags)), as the block is currently
          defined.  Other timestamps may be added in the future.
```

I noticed that stream-zip only uses the ancient MS-DOS timestamp format:

https://github.com/uktrade/stream-zip/blob/31245ce4f89aeede3e260db1430f4fb42911a51d/stream_zip.py#L378-L391

Luckily, the format for UT is very simple. Here is an example implementation of the Extended Timestamp created by the Trac project in 2013, it's just a few lines of code:

https://trac.edgewall.org/changeset?reponame=&new=11813%40%2F&old=11810%40%2F

I had a look around the `stream-zip` source and found the "extra fields" but wasn't sure about the best way to fit this new data into the current architecture.

As a general overview, I think something like this makes sense:

- The internal `data_func()` currently takes the `mod_at_encoded` as parameter. Changing that to taking the raw `datetime` object instead would allow us to preserve the full datetime precision when passing information to the chosen metadata encoder (ZIP32/ZIP64).
- The `mod_at_encoded = modified_at_struct.pack(` conversion could be moved to a small helper function instead, which is called by both ZIP32 and ZIP64 encoders to generate the MS-DOS timestamp struct.
- Adding a function which does the the Universal Timestamp extra-data encoding, based on the same technique as Trac. Taking a Unix Timestamp integer as input (most likely have to wrap that in `int(round())` to round it and throw away float microsecond precision). And marking it with `Flags = 1` meaning "only modification time is present" (same as what Trac did), since it's pointless and totally overkill to store the access time and creation time.
- Converting the `datetime` object to a Unix timestamp is doable via `.timestamp()`. There's some extra consideration when the `datetime` object lacks a timezone (when its `.tzinfo` is empty). In that case, it's possible to tell it to use the computer's local timezone as reference for the conversion, by doing `.astimezone(tz=None).timestamp()`. However, the `.astimezone()` call doesn't seem necessary. I've seen people say that it's necessary, but personally it seems to work identically in Python 3.10.7 without doing that explicit conversion. I get the exact same resulting timestamp either way. Perhaps it's been changed to "automatically interpret datetimes without tz as local time" nowadays in recent Python versions. Here are two examples of a datetime without timezone to show what I'm seeing. So if all Python versions supported by `stream-zip` work this way, then the `.astimezone()` call is pointless:
```
>>> datetime.fromisoformat('2021-01-01 21:01:12').astimezone().timestamp()
1609531272.0
>>> datetime.fromisoformat('2021-01-01 21:01:12').timestamp()
1609531272.0
```
- _Edit: I ran some more tests. It seems the only purpose of `.astimezone()` is to fill in the `tzinfo` for use in `.strftime("%z %Z")`, which otherwise would output empty strings. It still doesn't make any difference for the UNIX `.timestamp()`. You may want to try it on the oldest Python version that the library supports too, just to be sure that it isn't needed._
- Ensuring that the ZIP32 and ZIP64 encoders write that UT extra-data field in both the local headers and the central metadata, since it belongs in both places.

This would allow `stream-zip` created ZIP files to retain the correct file timestamps no matter where in the world the person who extracts them lives. :)

Edit: I noticed that the crufty, old Python [zipfile](https://github.com/python/cpython/blob/main/Lib/zipfile/__init__.py) doesn't even make an attempt to read or write the accurate UNIX timestamp. Yet another reason to dislike the official library. ;) If someone wants to read the UT "extra" timestamp field via that library, the data is in the `ZipInfo.extra` field but must be manually decoded, meh. They lazily [defer](https://docs.python.org/3/library/zipfile.html#zipfile.ZipInfo.extra) to the ZIP APPNOTE. [Section 4.5 Extensible data fields](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) explains the decoding.

**Comment by Arcitec** [comment]
Since someone, someday is going to read this and wonder how to read precise UNIX timestamps via Python's zipfile library, I'm including my implementation here.

It correctly parses the "extra data" fields and looks for the UNIX timestamp (0x5455) field, and extracts the modification time if available.

I'm placing it in the public domain. Anyone is welcome to use this for any purposes.

```py
from typing import Optional
import io
import struct
import zipfile

with zipfile.ZipFile("foo.zip") as zf:
    for f in zf.infolist():
        # Extract the "Extended Timestamp" if available.
        # SEE: https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT (section 4.5)
        # SEE: https://opensource.apple.com/source/zip/zip-6/unzip/unzip/proginfo/extra.fld
        ut_mtime: Optional[int] = None
        bytes_read = 0
        bytes_total = len(f.extra)
        fp = io.BytesIO(f.extra)
        while bytes_read < bytes_total:
            header_id = struct.unpack_from("<H", fp.read(2))[0]
            data_size = struct.unpack_from("<H", fp.read(2))[0]

            seek_skip = 0
            if header_id == 0x5455:  # UT.
                # Check for modification time availability (bit 1).
                # NOTE: Due to bugs in Python's ZipFile library, it's
                # impossible to read anything more than the modification
                # time. Python only reads the "central record" version
                # of the extra-data, which ONLY holds the `mtime`, but
                # the `flags` refers to the other timestamps too (which
                # are ONLY stored in the "local record" "extra" header).
                if data_size > 0:
                    ut_flags = struct.unpack_from("<B", fp.read(1))[0]
                    seek_skip = data_size - 1
                    if ut_flags & 0b1 > 0:
                        ut_mtime = struct.unpack_from("<i", fp.read(4))[0]
                        seek_skip -= 4

                # We only care about the UT field.
                break
            else:
                # Skip all remaining data for this field.
                seek_skip = data_size

            if seek_skip > 0:
                fp.seek(seek_skip, io.SEEK_CUR)

            bytes_read += 4 + data_size

        # You should always prefer `ut_mtime` if not None, else fall back
        # to using the inaccurate `f.date_time` MS-DOS timestamp.
        print(ut_mtime, f.date_time)
```

**Comment by michalc** [comment]
> All ZIP extraction utilities interpret the MS-DOS timestamp as local time

Ah I don't think I was aware of this. Slightly annoying that to solve it we would have to make ZIP files bigger for everyone (at least without a more complex API...), but it's probably worth it. I'm imagining some cases where you unzip and the files appear to have been modified in the future even? Very odd right now if that's the case.

> The internal data_func() currently takes the mod_at_encoded as parameter. Changing that to taking the raw datetime object instead would allow us to preserve the full datetime precision when passing information to the chosen metadata encoder (ZIP32/ZIP64).

I think I lean a bit to passing in mod_at_encoded (maybe renamed to mod_at_ms_dos) and mod_at_unix_extra. If we're only concerned with modification time, then both local and central directory extras are the same I think, and this I think better matches the existing pattern where encoding of things that are the same between all of the modes are done outside of data_func()

**Comment by michalc** [comment]
Done in https://github.com/uktrade/stream-zip/pull/62 and released in https://pypi.org/project/stream-zip/0.0.64/

Thanks for the report!
