### ISSUE TITLE
Add file like object interface

### ISSUE THREAD

**Issue by jameschristopher** [uktrade/stream-zip#84]
This is a feature request to add a File Like Object interface that simply takes the same args and then wraps the generator output of `stream_zip`. Specifically the `.read` method might be the only meaningful method to add. This can be very handy for libraries like `boto3` where you want to do a multipart streaming upload thus preserving the low memory functionality that is core to using an awesome library like `stream-zip`.

Kind of imaging something like:
```
import boto3
from stream_zip import stream_zip_as_flo

zipped_flo = stream_zip_as_flo(...)
s3_client = boto3.client("s3", config=AWS_CONFIG)
s3_client.upload_fileobj(
    zipped_flo, 
    AWS_BUCKET_NAME, 
    object_key, 
    Config=TransferConfig(
        multipart_threshold=...,
        multipart_chunksize=...,
        io_chunksize=...,
        use_threads=False
    )
)
```

I'm doing my own implementation in my project but am not an expert. I'd be willing to contribute a PR in tandem with someone who knows generators and the ins-and-outs of this library.

Thanks for the great library!

**Comment by michalc** [comment]
Ah so it's not in the library itself, but there is https://stream-zip.docs.trade.gov.uk/output-examples/#file-like-object that shows how to convert an iterable of bytes to a file like object, and then also https://stream-zip.docs.trade.gov.uk/output-examples/#upload-to-s3 that shows how to use it for uploads to S3

On having it in stream-zip itself... I'm torn. I can see it would be useful, but I think the fact that it'll only useful to some, and the fact that the functionality can be achieved without it being in stream-zip as you (and the documentation) say, make me lean to not having it in the code base.

**Comment by jameschristopher** [comment]
Yeah, I actually used the two examples as inspiration for my implementation. There may even be a library out there that is explicitly focused on turning generators into FLOs. I just wanted to bring it up since I didn't see any discussion on it in the issues. Feel free to close this if at this time it is out of scope.

**Comment by michalc** [comment]
> There may even be a library out there that is explicitly focused on turning generators into FLOs

On this, I would love for it to be in the standard library... feels like the thing that would be in https://docs.python.org/3/library/io.html maybe? I've nosed around but never found anything.

> Yeah, I actually used the two examples as inspiration for my implementation. 

That is their purpose really.

On being out of scope... might ponder a bit more. Really want the library to keep its focus, and not contain converters for all possible output (and input) types. But: needing a file-like object is also quite a common requirement, and it's a bit fiddly to make one, so maybe this should be an exception.

**Comment by michalc** [comment]
Have now asked if the conversion should be in boto3: https://github.com/boto/boto3/discussions/3819

**Comment by michalc** [comment]
I have pondered a bit, and even if boto3 won't end up adding it, I am pro it not being in this stream-zip to keep it minimal. This isn't necessarily a permanent decision, but closing this issue in the meantime.

**Comment by jameschristopher** [comment]
For reference by anyone in the future here is my implementation of a file-like-object wrapper class (different from the one referenced in the docs which would cause an exception in some cases)
```python
generator = stream_zip(remote_files(specs), chunk_size=chunk_size)

class StreamingZipFile:
    def __init__(self, generator, chunk_size=CHUNK_SIZE):
        self.generator = generator
        self.buffer = b""
  
    def read(self, bytes=None):
        while bytes is not None and len(self.buffer) < bytes:
            try:
                self.buffer += next(self.generator)
            except StopIteration:
                break
        result = self.buffer[:bytes]
        self.buffer = self.buffer[bytes:]
        return result
```

**Comment by michalc** [comment]
> (different from the one referenced in the docs which would cause an exception in some cases)

Ah - when would it cause an exception?

**Comment by michalc** [comment]
Also I wonder if there is a performance issue with the implementation of `StreamingZipFile` above. Could the `+=` involve quite a lot of copying of bytes since each time the whole bytes instance has to be contiguous in memory? Say using the default chunk size of stream-zip, this would involve copying

0 the first iteration I suspect (since I think Python would avoid copying in this special case)
64 KiB + 64 KiB the second
64 KiB + 64 KiB + 64 KiB the third
etc

And so end up processing quite a lot.

From a quick test the default value of `bytes` passed into the `read` function of the file like object from upload_fileobj is `8388608` - the `multipart_chunksize`. And some very rough calculations suggest that this would result over ~500 MiB processed internally for an 8MiB file. And it would get much bigger for a larger `multipart_chunksize`.

**Comment by jameschristopher** [comment]
I'll see if I can dig up the error in my logs (it was a while ago).

That's actually a very good point about the `+=` operand!  You're absolutely right. That being said I've processed some relatively large zipfiles with it (>3 GB) without seeing significant memory inflation. I may run a test with the example from the docs again, and see 1) if i can reproduce the error, and 2) see what's going on under the hood with my implementation.

**Comment by michalc** [comment]
Ah so I wouldn’t have thought it had a lot of memory inflation, more performance in terms of cpu usage/speed since it won’t have the entire 500MiB in memory at once, just in total over the construction of one 8MiB upload part it would have copied 500MiB internally.

**Comment by jameschristopher** [comment]
I will test that too, and I'll test it outside of my co's application because there could be some underlying infrastructure stuff that could be hiding some things.

**Comment by jameschristopher** [comment]
Now when it comes to profiling python we are starting to get out of my area of expertise. So I don't feel comfortable posting any strong conclusions, but a basic cProfile shows the timing of my implementation and the docs to depend on the size parameter passed into the `.read` method. As you lower the value passed into the `.read` method my implementation begins to perform better than the docs implementation. And as the parameter value is increased the docs implementation performs better. The differences in both ways become greater as the magnitude of the parameter increases.

Here is a surprise: With my implementation is that as you pointed out the `bytes` object is immutable and using the `+=` would result in a copy. I tried using a `bytearray` instead which is mutable and using the `.extend` method, which should modify it inplace not resulting a copy. Both methods performed about the same, so I'm not sure if some optimization is happening under the hood in python.

I can email the ipython notebook to you if you want.

**Comment by michalc** [comment]
> Here is a surprise: With my implementation is that as you pointed out the bytes object is immutable and using the += would result in a copy. I tried using a bytearray instead which is mutable and using the .extend method, which should modify it inplace not resulting a copy. Both methods performed about the same, so I'm not sure if some optimization is happening under the hood in python.

I guess the doesn't surprise my too much - an extend would still have to re-allocate the bytes of the bytearray in most cases I think? The (im)mutability I don't think comes into it I suspect - it's more the fact that in both the total memory allocated needs to be contiguous, and there is no way as far as I know to allocate memory next to already allocated memory, so each would need a copy

> As you lower the value passed into the .read method my implementation begins to perform better than the docs implementation. And as the parameter value is increased the docs implementation performs better

Ah good to know - do you have ball park figure of the point at which they perform about the same?

> I can email the ipython notebook to you if you want.

Ideally it would attached to a comment in this issue if possible to keep things public?

**Comment by michalc** [comment]
Related: have now published https://github.com/uktrade/to-file-like-obj, with an example of using it with `upload_fileobj` to upload to S3 in its README
