### ISSUE TITLE
Progress indicator

### ISSUE THREAD

**Issue by me21** [uktrade/stream-zip#86]
Would it be possible to obtain a progress indicator somehow? Like the number of files processed so far.

**Comment by michalc** [comment]
Hi @me21,

So I suspect the answer is yes, but do you have more context? Where are files pulled from, sent to, and in what environment? Maybe some example code that you would like to add a progress indicator to?

Thanks,

Michal

**Comment by me21** [comment]
I load files from local storage and they are combined in single zip file stream which is then saved to another local storage (e.g. flash drive).

In other words, it is used as a backup or copy of application data which is gradually accumulating and may reach gigabytes in size if backed up seldom. So a progress indicator would be useful.

It runs on a single board computer with a web UI, but I don't think it really matters much.

I would start an async task which would periodically update the progress indicator.

**Comment by michalc** [comment]
So it's not from an async task, but something like this that uses tqdm?

```python
from datetime import datetime
from stat import S_IFREG
from stream_zip import stream_zip, ZIP_32
from tqdm import tqdm

def member_files():
    modified_at = datetime.now()
    mode = S_IFREG | 0o600

    file_1_bytes = (b'*' * 1000 for _ in range(0, 100000))
    file_1_total = 1000 * 100000

    file_2_bytes = (b'-' * 4000 for _ in range(0, 400000))
    file_2_total = 4000 * 400000

    def with_progress(pbar, chunks):
        for chunk in chunks:
            pbar.update(len(chunk))
            yield chunk

    with tqdm(unit='B', unit_scale=True, unit_divisor=1024, total=file_1_total + file_2_total) as pbar:
        yield ('file-1.txt', modified_at, mode, ZIP_32, with_progress(pbar, file_1_bytes))
        yield ('file-2.txt', modified_at, mode, ZIP_32, with_progress(pbar, file_2_bytes))

for zipped_chunk in stream_zip(member_files()):
    pass
```

https://github.com/uktrade/stream-zip/assets/13877/10d17ed1-a662-4164-bd8d-e3d88a9ed3f2

**Comment by me21** [comment]
Thank you. I think your example can be tweaked for my case of webui as well.

**Comment by stuaxo** [comment]
This is a neat recipe, I wonder if it's worth including in the codebase or docs somewhere ?

**Comment by stuaxo** [comment]
It's on the procrastination list (in my head), so just need to find something more important and I'll get to it via the power of procrastination 👍
