### ISSUE TITLE
Distribute it on conda-forge

### ISSUE THREAD

**Issue by sbrunato** [uktrade/stream-zip#90]
Hello, and thanks for the work on this library.

Do you plan to distribute it on conda-forge, like it is done for [stream-unzip](https://anaconda.org/conda-forge/stream-unzip) ?
Thanks

**Comment by michalc** [comment]
Hello @sbrunato,

Have to admit I wasn't even aware stream-unzip was on conda-forge. No particular plans no...

... but to ask, what's the benefit? I'm no conda expert, but I thought it was fairly straightforward to install from pypi (where stream-zip is currently published) when using conda

**Comment by michalc** [comment]
Actually... looks like we don't need to be involved. Anyone can submit packages to conda-forge? Looking at how I think stream-unzip got there https://github.com/conda-forge/staged-recipes/pull/20058, you don't need any particular affiliation or approval from the people that actually write/maintain the code

**Comment by sbrunato** [comment]
> ... but to ask, what's the benefit?

We introduced `stream-zip` as dependency of https://github.com/CS-SI/eodag and need all dependencies to be available on `conda` to be able to build and publish a new version.

> Actually... looks like we don't need to be involved.

Yes, you are true. We also can publish the conda recipe on our own if needed.
Thanks for the anwser.

**Comment by michalc** [comment]
(Mostly) understood. So realistically this isn't going to happen from our end any time soon.

If you wish to unblock the publish the new version of https://github.com/CS-SI/eodag to conda, I have no objections on you publishing a version of stream-zip to conda-forge (and I don't think I could particularly stop you even if I had objections!)

Will close this issue since I don't think there is any more action to take here.

**Comment by michalc** [comment]
> So realistically this isn't going to happen from our end any time soon.

It's a bit easier than I feared. Giving publishing on conda-forge a go now in  https://github.com/conda-forge/staged-recipes/pull/24588

**Comment by michalc** [comment]
Now published to conda-forge https://anaconda.org/conda-forge/stream-zip
